import type { Metadata } from "next";

import "../../globals.css";
import SearchInput from "@/components/shop/SearchInput";

export const metadata: Metadata = {
  title: "eCommerce",
  description: "Generated by eCommerce",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SearchInput />
        {children}
      </body>
    </html>
  );
}
