import type { Metadata } from "next";

import "../globals.css";
import Navbar from "@/components/commerce/navigation/Navbar";

export const metadata: Metadata = {
  title: {
    template: "%s | eCommerce",
    default: "Shop",
  },
  description: "Generated by eCommerce",
};

export default function CommerceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
