import type { Metadata } from "next";

import "../globals.css";
import Navbar from "@/components/commerce/navigation/Navbar";
import { CartContext, CartProvider } from "../context/CartContext";
import { WishListProvider } from "../context/WishListContext";

export const metadata: Metadata = {
  title: {
    template: "%s | eCommerce",
    default: "Shop",
  },
  description: "Generated by eCommerce",
};

export default function CommerceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <WishListProvider>
        <html lang="en">
          <body>
            <Navbar />
            {children}
          </body>
        </html>
      </WishListProvider>
    </CartProvider>
  );
}
